using System.ComponentModel;

//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoneCases.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customers : INotifyPropertyChanged
    {
        private Companies _Company;
        private string _Name;
        private string _PhoneNumber;

        public int Id { get; set; }
        public string Name { get { return this._Name; } set { if (value != this._Name) { this._Name = value; NotifyPropertyChanged("Name"); };} }
        public string PhoneNumber { get { return this._PhoneNumber; } set { if (value != this._PhoneNumber) { this._PhoneNumber = value; NotifyPropertyChanged("PhoneNumber"); };} }

        public int CompanyId { get; set; }

        public virtual Companies Company { get { return this._Company; } set { if (value != this._Company) { this._Company = value; NotifyPropertyChanged("Company"); };} }

        public event PropertyChangedEventHandler PropertyChanged;
        private void NotifyPropertyChanged(String propertyName = "")
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
}
