//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoneCases.WPFGUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaseTags
    {
        public int Id { get; set; }
        public int TagsId { get; set; }
        public int CasesId { get; set; }
    
        public virtual Tags Tag { get; set; }
        public virtual Cases Case { get; set; }
    }
}
