//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cases
    {
        public Cases()
        {
            this.CaseTags = new HashSet<CaseTags>();
        }
    
        public int Id { get; set; }
        public string Info { get; set; }
        public string StartTime { get; set; }
        public string EndTime { get; set; }
        public string CloseTime { get; set; }
        public string Closed { get; set; }
        public string Active { get; set; }
        public string Reconnect { get; set; }
    
        public virtual ICollection<CaseTags> CaseTags { get; set; }
        public virtual Customers Customers { get; set; }
        public virtual Users Users { get; set; }
    }
}
