//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModelContainer : DbContext
    {
        public ModelContainer()
            : base("name=ModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Customers> CustomersSet { get; set; }
        public DbSet<Cases> CasesSet { get; set; }
        public DbSet<Companies> CompaniesSet { get; set; }
        public DbSet<Locations> LocationsSet { get; set; }
        public DbSet<CaseTags> CaseTagsSet { get; set; }
        public DbSet<CompanyType> CompanyTypeSet { get; set; }
        public DbSet<Users> UsersSet { get; set; }
    }
}
